[package]
name = "safe-string"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
description = "Provides a safe interface for interacting with multi-byte strings in Rust, namely IndexedStr, IndexedString, and IndexedSlice"
license = "MIT"
